spring:
  application:
    name: javachat
  datasource:
    url: jdbc:mysql://mysql:3306/jchat
    username: root
    password: tajneHaslo
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always